version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: ""
      prefix-development: "dev"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: leaflet
      - dependency-name: vue2-leaflet
      - dependency-name: "@fortawesome/fontawesome-free"
      - dependency-name: less-loader
