plugins:
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/exec'
    - successCmd: "echo 'release=yes' >> $GITHUB_OUTPUT; echo $GITHUB_OUTPUT"
      failCmd: "echo 'release=no' >> $GITHUB_OUTPUT; echo $GITHUB_OUTPUT"
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: .
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - package.json
  - '@eclass/semantic-release-sentry-releases'
branches:
  - dev
