plugins:
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/exec'
    - successCmd: >
        echo 'release=yes' >> $GITHUB_OUTPUT;
        echo 'new_release_version=${nextRelease.version}' >> $GITHUB_OUTPUT;
        echo 'new_release_git_tag=${nextRelease.gitTag}' >> $GITHUB_OUTPUT
      failCmd: "echo 'release=no' >> $GITHUB_OUTPUT"
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: .
  - '@semantic-release/github'
  - - '@codedependant/semantic-release-docker'
    - dockerImage: warframe-hub
      dockerRegistry: ghcr.io
      dockerProject: wfcd
      dockerPlatform:
        - 'linux/amd64'
        - 'linux/arm64'
  - '@eclass/semantic-release-sentry-releases'
branches:
  - dev
