name: CI
on:
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  commitlint:
    name: Commit messages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Validate PR commit messages
      run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Use Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Run linters
      run: npm run lint
  test:
    name: E2E
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - 'chrome'
#          - 'firefox'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Run Cypress E2E
      uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
      with:
        start: npm run dev
        wait-on: 'http://localhost:8742'
        browser: ${{ matrix.browser }}
        command: npm run test:e2e
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: failure()
      with:
        name: screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: videos
        path: cypress/videos
  component:
    name: Component
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Run Cypress component tests
      uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
      with:
        browser: chrome
        component: true
        command: npm run test:component
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: failure()
      with:
        name: component-screenshots
        path: cypress/screenshots
